# This is a basic workflow to help you get started with Actions
name: README

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  snake-animation:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: travishenson
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Publish Snake Animation SVG
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
